### ISSUE TITLE
Action should take type as a Type parameter

### ISSUE THREAD

**Issue by fenilkanjani** [action-land/action-land#12]
As of now, while creating an action, we provide a Type parameter for value. But the type can only be `string | number`. For e.g. :

```typescript
action<TestValue>('testType')
```

Instead it should be:
```typescript
action<TestType, TestValue>('testType')
```

**Comment by tusharmath** [comment]
Fixed in https://github.com/action-land/action-land/commit/1a595927b28f89f98ec405bd7ba64974a580de26
