### ISSUE TITLE
Can't apply Smitten emit to event callback which takes 0 arguments

### ISSUE THREAD

**Issue by shwetdream11** [action-land/action-land#4]
On any event callback function which takes 0 arguments, emit can't be called directly.

Doesn't work
`
<Button onPress={emitter.of('buttonPressed').emit}>
</Button
`

Workaround
`
<Button onPress={emitter.of('buttonPressed').emit as () => void}>
</Button
`

making obj as optional solves the issue

**Comment by jLouzado** [comment]
@shwetdream11 is this still an issue? Cuz we have loads of uses like this in PWA, atleast...

Closing issue for now, let me know if it needs to be re-opened.
